name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/add-user-group-man-man.png
    - assets/page-1/images/card-wallet.png
    - assets/page-1/images/wi-fi.png
    - assets/page-1/images/notepad.png
    - assets/page-1/images/battery.png
    - assets/page-1/images/chevrons-chevron-right.png
    - assets/page-1/images/choice.png
    - assets/page-1/images/boxes.png
    - assets/page-1/images/chevrons-chevron-right-YEd.png
    - assets/page-1/images/chevrons-chevron-right-89X.png
    - assets/page-1/images/cheque.png
    - assets/page-1/images/battery-KXP.png
    - assets/page-1/images/histogram.png
    - assets/page-1/images/files-file-text.png
    - assets/page-1/images/chevrons-chevron-right-kmP.png
    - assets/page-1/images/shopping-cart.png
    - assets/page-1/images/notepad-XYM.png
    - assets/page-1/images/bulleted-list.png
    - assets/page-1/images/dashboardcustomizefill0wght400grad0opsz48-1.png
    - assets/page-1/images/personfill0wght400grad0opsz48-1.png
    - assets/page-1/images/chevrons-chevron-up.png
    - assets/page-1/images/svgexport-19.png
    - assets/page-1/images/popular-menu.png
    - assets/page-1/images/menufill0wght400grad0opsz48-1.png
    - assets/page-1/images/menufill0wght400grad0opsz48-1-7LV.png
    - assets/page-1/images/popular-menu-BCV.png
    - assets/page-1/images/background.png
    - assets/page-1/images/wi-fi-hz1.png
    - assets/page-1/images/chevrons-chevron-right-Yky.png
    - assets/page-1/images/chevrons-chevron-right-JRF.png
    - assets/page-1/images/wi-fi-FMs.png
    - assets/page-1/images/group-5-wRT.png
    - assets/page-1/images/svgexport-28.png
    - assets/page-1/images/image-2.png
    - assets/page-1/images/dashboardcustomizefill0wght400grad0opsz48-1-wXf.png
    - assets/page-1/images/chevrons-chevron-right-cVP.png
    - assets/page-1/images/wi-fi-9tD.png
    - assets/page-1/images/popular-tag.png
    - assets/page-1/images/combined-shape.png
    - assets/page-1/images/background-FV3.png
    - assets/page-1/images/group-5.png
    - assets/page-1/images/navigations-map-pin.png
    - assets/page-1/images/wi-fi-vX3.png
    - assets/page-1/images/combined-shape-U2m.png
    - assets/page-1/images/wi-fi-BSy.png
    - assets/page-1/images/group-14.png
    - assets/page-1/images/groups2fill0wght400grad0opsz48-1.png
    - assets/page-1/images/combined-shape-F6Z.png
    - assets/page-1/images/battery-bAR.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/svgexport-22.png
    - assets/page-1/images/menufill0wght400grad0opsz48-1-ch7.png
    - assets/page-1/images/combined-shape-MRj.png
    - assets/page-1/images/battery-REZ.png
    - assets/page-1/images/chevrons-chevron-right-Vr1.png
    - assets/page-1/images/merchant-account.png
    - assets/page-1/images/dashboardcustomizefill0wght400grad0opsz48-1-kG9.png
    - assets/page-1/images/bg.png
    - assets/page-1/images/background-4wb.png
    - assets/page-1/images/product.png
    - assets/page-1/images/wi-fi-ijs.png
    - assets/page-1/images/svgexport-24.png
    - assets/page-1/images/combined-shape-CTB.png
    - assets/page-1/images/chevrons-chevron-right-4iu.png
    - assets/page-1/images/combined-shape-rem.png
    - assets/page-1/images/bg-7EZ.png
    - assets/page-1/images/personfill0wght400grad0opsz48-1-DHb.png
    - assets/page-1/images/chevrons-chevron-right-he1.png
    - assets/page-1/images/popular-settings.png
    - assets/page-1/images/bg-Z4M.png
    - assets/page-1/images/summarizefill0wght400grad0opsz48-1.png
    - assets/page-1/images/wi-fi-EXb.png
    - assets/page-1/images/close.png
    - assets/page-1/images/chevrons-chevron-up-Bp5.png
    - assets/page-1/images/combined-shape-ULZ.png
    - assets/page-1/images/battery-Ar5.png
    - assets/page-1/images/battery-7T7.png
    - assets/page-1/images/popular-menu-WBb.png
    - assets/page-1/images/chevrons-chevron-up-PmB.png
    - assets/page-1/images/dashboardcustomizefill0wght400grad0opsz48-1-2UZ.png
    - assets/page-1/images/battery-FRb.png
    - assets/page-1/images/account-user.png
    - assets/page-1/images/combined-shape-Vqj.png
    - assets/page-1/images/messaging-edit.png
    - assets/page-1/images/battery-abb.png
    - assets/page-1/images/dashboardcustomizefill0wght400grad0opsz48-1-Vds.png
    - assets/page-1/images/messaging-edit-2.png
    - assets/page-1/images/groups2fill0wght400grad0opsz48-1-yJ9.png
    - assets/page-1/images/summarizefill0wght400grad0opsz48-1-7fF.png
    - assets/page-1/images/battery-tZX.png
    - assets/page-1/images/battery-Fey.png
    - assets/page-1/images/popular-trash-2.png
    - assets/page-1/images/groups2fill0wght400grad0opsz48-1-u21.png
    - assets/page-1/images/svgexport-21.png
    - assets/page-1/images/background-L7K.png
    - assets/page-1/images/chevrons-chevron-down.png
    - assets/page-1/images/wi-fi-TLM.png
    - assets/page-1/images/combined-shape-cU9.png
    - assets/page-1/images/svgexport-23.png
    - assets/page-1/images/personfill0wght400grad0opsz48-1-jHs.png
    - assets/page-1/images/battery-SCH.png
    - assets/page-1/images/dashboardcustomizefill0wght400grad0opsz48-1-GBK.png
    - assets/page-1/images/battery-ZAR.png
    - assets/page-1/images/chevrons-chevron-up-Jth.png
    - assets/page-1/images/wi-fi-58m.png
    - assets/page-1/images/combined-shape-PfF.png
    - assets/page-1/images/plus-icon.png
    - assets/page-1/images/groups2fill0wght400grad0opsz48-1-VCV.png
    - assets/page-1/images/summarizefill0wght400grad0opsz48-1-2CR.png
    - assets/page-1/images/combined-shape-ytM.png
    - assets/page-1/images/groups2fill0wght400grad0opsz48-1-yEh.png
    - assets/page-1/images/groups2fill0wght400grad0opsz48-1-nhw.png
    - assets/page-1/images/business-credit-card.png
    - assets/page-1/images/menufill0wght400grad0opsz48-1-pXK.png
    - assets/page-1/images/wi-fi-M1T.png
    - assets/page-1/images/group-5-VdT.png
    - assets/page-1/images/summarizefill0wght400grad0opsz48-1-2dP.png
    - assets/page-1/images/combined-shape-z4y.png
    - assets/page-1/images/battery-EdX.png
    - assets/page-1/images/dashboardcustomizefill0wght400grad0opsz48-1-LgZ.png
    - assets/page-1/images/menufill0wght400grad0opsz48-1-ZDs.png
    - assets/page-1/images/messaging-edit-2-wER.png
    - assets/page-1/images/popular-trash-2-Wnd.png
    - assets/page-1/images/summarizefill0wght400grad0opsz48-1-AVo.png
    - assets/page-1/images/background-Myb.png
    - assets/page-1/images/menufill0wght400grad0opsz48-1-REh.png
    - assets/page-1/images/background-r2V.png
    - assets/page-1/images/wi-fi-q2q.png
    - assets/page-1/images/groups2fill0wght400grad0opsz48-1-V4m.png
    - assets/page-1/images/personfill0wght400grad0opsz48-1-CdP.png
    - assets/page-1/images/popular-menu-jYm.png
    - assets/page-1/images/summarizefill0wght400grad0opsz48-1-Gob.png
    - assets/page-1/images/personfill0wght400grad0opsz48-1-csT.png
    - assets/page-1/images/popular-menu-5XP.png
    - assets/page-1/images/wi-fi-dz9.png
    - assets/page-1/images/combined-shape-Yx1.png
    - assets/page-1/images/battery-tPb.png
    - assets/page-1/images/combined-shape-LmP.png
    - assets/page-1/images/menufill0wght400grad0opsz48-1-Lim.png
    - assets/page-1/images/image.png
    - assets/page-1/images/popular-menu-22V.png
    - assets/page-1/images/bg-pPs.png
    - assets/page-1/images/wi-fi-FTo.png
    - assets/page-1/images/popular-menu-akh.png
    - assets/page-1/images/summarizefill0wght400grad0opsz48-1-NKB.png
    - assets/page-1/images/bg-8F3.png
    - assets/page-1/images/background-p89.png
    - assets/page-1/images/combined-shape-Dzq.png
    - assets/page-1/images/personfill0wght400grad0opsz48-1-cQh.png
    - assets/page-1/images/icon.png
    - assets/page-1/images/icon-8Dw.png
    - assets/page-1/images/groups2fill0wght400grad0opsz48-1-MF7.png
    - assets/page-1/images/personfill0wght400grad0opsz48-1-82u.png
    - assets/page-1/images/bg-o2H.png
    - assets/page-1/images/image-mX7.png
    - assets/page-1/images/bg-cAD.png
    - assets/page-1/images/bg-MtV.png
    - assets/page-1/images/bg-VHb.png
    - assets/page-1/images/background-iJ5.png
    - assets/page-1/images/battery-SpH.png
    - assets/page-1/images/text-book.png
    - assets/page-1/images/combined-shape-aJ5.png
    - assets/page-1/images/groups2fill0wght400grad0opsz48-1-pCR.png
    - assets/page-1/images/dashboardcustomizefill0wght400grad0opsz48-1-x3j.png
    - assets/page-1/images/menufill0wght400grad0opsz48-1-6fj.png
    - assets/page-1/images/summarizefill0wght400grad0opsz48-1-SzV.png
    - assets/page-1/images/icon-98D.png
    - assets/page-1/images/background-u7P.png
    - assets/page-1/images/messaging-edit-bW1.png
    - assets/page-1/images/icon-AJD.png
    - assets/page-1/images/popular-menu-oMB.png
    - assets/page-1/images/personfill0wght400grad0opsz48-1-65P.png
    - assets/page-1/images/wi-fi-o7P.png
    - assets/page-1/images/personfill0wght400grad0opsz48-1-eXK.png
    - assets/page-1/images/summarizefill0wght400grad0opsz48-1-Ny7.png
    - assets/page-1/images/dashboardcustomizefill0wght400grad0opsz48-1-mVK.png
    - assets/page-1/images/image-epZ.png
    - assets/page-1/images/popular-menu-7J1.png
    - assets/page-1/images/menufill0wght400grad0opsz48-1-dds.png
    - assets/page-1/images/misc-power.png
    - assets/page-1/images/menufill0wght400grad0opsz48-1-ySH.png
    - assets/page-1/images/battery-mBf.png
    - assets/page-1/images/summarizefill0wght400grad0opsz48-1-Wnd.png
    - assets/page-1/images/wi-fi-ch7.png
    - assets/page-1/images/personfill0wght400grad0opsz48-1-2Rw.png
    - assets/page-1/images/notifications-info.png
    - assets/page-1/images/groups2fill0wght400grad0opsz48-1-cuF.png
    - assets/page-1/images/battery-p3b.png
    - assets/page-1/images/background-LKs.png
    - assets/page-1/images/wi-fi-qvZ.png
    - assets/page-1/images/popular-menu-LLZ.png
    - assets/page-1/images/notifications-info-Guo.png
    - assets/page-1/images/bg-auP.png
    - assets/page-1/images/dashboardcustomizefill0wght400grad0opsz48-1-QdP.png
    - assets/page-1/images/combined-shape-dkM.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
